import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ThemeRegistry from "./ThemeRegistry";

const inter = Inter({ subsets: ["latin"] });
import Navbar from "./components/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeRegistry>
            <Navbar />
            {children}
          </ThemeRegistry>
        </body>
      </html>
    </ClerkProvider>
  );
}
